// Mocks generated by Mockito 5.4.4 from annotations
// in pontifex_archive/test/core/data/providers/document_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pontifex_archive/src/core/data/models/pope.dart' as _i5;
import 'package:pontifex_archive/src/core/data/providers/leigo_fm_provider.dart'
    as _i2;
import 'package:pontifex_archive/src/core/data/providers/popes_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLeigoFmProvider_0 extends _i1.SmartFake
    implements _i2.LeigoFmProvider {
  _FakeLeigoFmProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PopeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopeProvider extends _i1.Mock implements _i3.PopeProvider {
  MockPopeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LeigoFmProvider get leigofm => (super.noSuchMethod(
        Invocation.getter(#leigofm),
        returnValue: _FakeLeigoFmProvider_0(
          this,
          Invocation.getter(#leigofm),
        ),
      ) as _i2.LeigoFmProvider);

  @override
  _i4.Future<List<_i5.Pope>> fetchPopes() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopes,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Pope>>.value(<_i5.Pope>[]),
      ) as _i4.Future<List<_i5.Pope>>);
}
