import 'package:flutter/material.dart';
import 'package:pontifex_archive/src/core/theme/extended_color.dart';

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color.fromARGB(255, 216, 202, 6),
      surfaceTint: Color(0xff516165),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffa0b1b5),
      onPrimaryContainer: Color(0xff162629),
      secondary: Color(0xff595f61),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffdfe5e6),
      onSecondaryContainer: Color(0xff444a4b),
      tertiary: Color(0xff625c6b),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffb3abbc),
      onTertiaryContainer: Color(0xff26212e),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffbf9f8),
      onSurface: Color(0xff1b1c1c),
      onSurfaceVariant: Color(0xff424849),
      outline: Color(0xff737879),
      outlineVariant: Color(0xffc2c7c9),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303031),
      inversePrimary: Color(0xffb8cace),
      primaryFixed: Color(0xffd4e6ea),
      onPrimaryFixed: Color(0xff0e1e21),
      primaryFixedDim: Color(0xffb8cace),
      onPrimaryFixedVariant: Color(0xff39494d),
      secondaryFixed: Color(0xffdee3e5),
      onSecondaryFixed: Color(0xff171d1e),
      secondaryFixedDim: Color(0xffc2c7c9),
      onSecondaryFixedVariant: Color(0xff424849),
      tertiaryFixed: Color(0xffe8dff1),
      onTertiaryFixed: Color(0xff1e1926),
      tertiaryFixedDim: Color(0xffccc3d5),
      onTertiaryFixedVariant: Color(0xff4a4453),
      surfaceDim: Color(0xffdbd9d9),
      surfaceBright: Color(0xfffbf9f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f3f3),
      surfaceContainer: Color(0xffefeded),
      surfaceContainerHigh: Color(0xffeae8e7),
      surfaceContainerHighest: Color(0xffe4e2e2),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color.fromARGB(255, 227, 227, 12),
      surfaceTint: Color(0xff516165),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff67777b),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff3e4445),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff6f7677),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff46404f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff797282),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff8c0009),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffda342e),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffbf9f8),
      onSurface: Color(0xff1b1c1c),
      onSurfaceVariant: Color(0xff3e4445),
      outline: Color(0xff5b6061),
      outlineVariant: Color(0xff767c7d),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303031),
      inversePrimary: Color(0xffb8cace),
      primaryFixed: Color(0xff67777b),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff4e5f62),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6f7677),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff575d5e),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff797282),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff605968),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffdbd9d9),
      surfaceBright: Color(0xfffbf9f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f3f3),
      surfaceContainer: Color(0xffefeded),
      surfaceContainerHigh: Color(0xffeae8e7),
      surfaceContainerHighest: Color(0xffe4e2e2),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(lightMediumContrastScheme());
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color.fromARGB(255, 227, 227, 12),
      surfaceTint: Color(0xff516165),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff364549),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff1d2325),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff3e4445),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff25202d),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff46404f),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffbf9f8),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff1f2526),
      outline: Color(0xff3e4445),
      outlineVariant: Color(0xff3e4445),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303031),
      inversePrimary: Color(0xffdeeff3),
      primaryFixed: Color(0xff364549),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff1f2f33),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff3e4445),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff282e2f),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff46404f),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff2f2a38),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffdbd9d9),
      surfaceBright: Color(0xfffbf9f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f3f3),
      surfaceContainer: Color(0xffefeded),
      surfaceContainerHigh: Color(0xffeae8e7),
      surfaceContainerHighest: Color(0xffe4e2e2),
    );
  }

  ThemeData lightHighContrast() {
    return theme(lightHighContrastScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromARGB(255, 227, 227, 12),
      surfaceTint: Color(0xffb8cace),
      onPrimary: Color(0xff233336),
      primaryContainer: Color(0xff8d9ea2),
      onPrimaryContainer: Color(0xff010e11),
      secondary: Color(0xffc2c7c9),
      onSecondary: Color(0xff2b3133),
      secondaryContainer: Color(0xff3a4042),
      onSecondaryContainer: Color(0xffcfd5d6),
      tertiary: Color(0xffccc3d5),
      onTertiary: Color(0xff332e3c),
      tertiaryContainer: Color(0xffa199aa),
      onTertiaryContainer: Color(0xff0f0b17),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff131314),
      onSurface: Color(0xffe4e2e2),
      onSurfaceVariant: Color(0xffc2c7c9),
      outline: Color(0xff8c9293),
      outlineVariant: Color(0xff424849),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe4e2e2),
      inversePrimary: Color(0xff516165),
      primaryFixed: Color(0xffd4e6ea),
      onPrimaryFixed: Color(0xff0e1e21),
      primaryFixedDim: Color(0xffb8cace),
      onPrimaryFixedVariant: Color(0xff39494d),
      secondaryFixed: Color(0xffdee3e5),
      onSecondaryFixed: Color(0xff171d1e),
      secondaryFixedDim: Color(0xffc2c7c9),
      onSecondaryFixedVariant: Color(0xff424849),
      tertiaryFixed: Color(0xffe8dff1),
      onTertiaryFixed: Color(0xff1e1926),
      tertiaryFixedDim: Color(0xffccc3d5),
      onTertiaryFixedVariant: Color(0xff4a4453),
      surfaceDim: Color(0xff131314),
      surfaceBright: Color(0xff393939),
      surfaceContainerLowest: Color(0xff0d0e0e),
      surfaceContainerLow: Color(0xff1b1c1c),
      surfaceContainer: Color(0xff1f2020),
      surfaceContainerHigh: Color(0xff292a2a),
      surfaceContainerHighest: Color(0xff343535),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromARGB(255, 227, 227, 12),
      surfaceTint: Color(0xffb8cace),
      onPrimary: Color(0xff08191c),
      primaryContainer: Color(0xff8d9ea2),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffc6cccd),
      onSecondary: Color(0xff111719),
      secondaryContainer: Color(0xff8c9293),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffd0c7d9),
      onTertiary: Color(0xff191421),
      tertiaryContainer: Color(0xffa199aa),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffbab1),
      onError: Color(0xff370001),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff131314),
      onSurface: Color(0xfffcfafa),
      onSurfaceVariant: Color(0xffc7cbcd),
      outline: Color(0xff9fa4a5),
      outlineVariant: Color(0xff7f8485),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe4e2e2),
      inversePrimary: Color(0xff3b4b4e),
      primaryFixed: Color(0xffd4e6ea),
      onPrimaryFixed: Color(0xff041317),
      primaryFixedDim: Color(0xffb8cace),
      onPrimaryFixedVariant: Color(0xff29393c),
      secondaryFixed: Color(0xffdee3e5),
      onSecondaryFixed: Color(0xff0c1213),
      secondaryFixedDim: Color(0xffc2c7c9),
      onSecondaryFixedVariant: Color(0xff313739),
      tertiaryFixed: Color(0xffe8dff1),
      onTertiaryFixed: Color(0xff130f1b),
      tertiaryFixedDim: Color(0xffccc3d5),
      onTertiaryFixedVariant: Color(0xff393442),
      surfaceDim: Color(0xff131314),
      surfaceBright: Color(0xff393939),
      surfaceContainerLowest: Color(0xff0d0e0e),
      surfaceContainerLow: Color(0xff1b1c1c),
      surfaceContainer: Color(0xff1f2020),
      surfaceContainerHigh: Color(0xff292a2a),
      surfaceContainerHighest: Color(0xff343535),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(darkMediumContrastScheme());
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromARGB(255, 227, 227, 12),
      surfaceTint: Color(0xffb8cace),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffbcced2),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xfff6fcfd),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffc6cccd),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xfffff9fe),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffd0c7d9),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xfffff9f9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffbab1),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff131314),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xfff7fbfd),
      outline: Color(0xffc7cbcd),
      outlineVariant: Color(0xffc7cbcd),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe4e2e2),
      inversePrimary: Color(0xff1d2c30),
      primaryFixed: Color(0xffd8eaee),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffbcced2),
      onPrimaryFixedVariant: Color(0xff08191c),
      secondaryFixed: Color(0xffe2e8e9),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffc6cccd),
      onSecondaryFixedVariant: Color(0xff111719),
      tertiaryFixed: Color(0xffede3f6),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffd0c7d9),
      onTertiaryFixedVariant: Color(0xff191421),
      surfaceDim: Color(0xff131314),
      surfaceBright: Color(0xff393939),
      surfaceContainerLowest: Color(0xff0d0e0e),
      surfaceContainerLow: Color(0xff1b1c1c),
      surfaceContainer: Color(0xff1f2020),
      surfaceContainerHigh: Color(0xff292a2a),
      surfaceContainerHighest: Color(0xff343535),
    );
  }

  ThemeData darkHighContrast() {
    return theme(darkHighContrastScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: textTheme.apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
      );

  List<ExtendedColor> get extendedColors => [];
}
