name: pontifex_archive
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+7
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  epub_view: ^3.2.0
  shared_preferences: ^2.3.2
  equatable: any
  google_fonts: ^6.2.1
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  flutter_localizations:
    sdk: flutter
  better_router: ^2.2.0
  collection: ^1.18.0
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.4
  get_it: ^7.7.0
  path_provider: ^2.1.3
  cv: ^0.2.20+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  slang_build_runner: ^3.31.0
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#071435"
    theme_color: "#071435"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

